use texas_e_store;

# customer

INSERT INTO customer (name, email, password) VALUES ('Sahan', 'sahan@gmail.com', '$2b$10$XJTjhQfCLlg4sCrakL.ih.DaeXTb7SjrltITr/x4WgscUubBDDMRq');
INSERT INTO customer (name, email, password) VALUES ('Nipuni', 'nipuni@gmail.com', '$2b$10$XJTjhQfCLlg4sCrakL.ih.DaeXTb7SjrltITr/x4WgscUubBDDMRq');
INSERT INTO customer (name, email, password) VALUES ('Kumesh', 'kumesh@gmail.com', '$2b$10$TtrjJrQQn0LkvNJc3wUxLeWmWgji3b23Jq4rgIbzDJ39VauVTR5Zy');
insert into customer (name, email, password) values ('Ellynn', 'epalphramand0@google.de', 'o8whSe');
insert into customer (name, email, password) values ('Joelle', 'jmenere1@dell.com', '68Sabtu');
insert into customer (name, email, password) values ('Natalina', 'netherson2@cbsnews.com', 'PGtROSfv');
insert into customer (name, email, password) values ('Selinda', 'scox3@opera.com', 'k1XUWz');
insert into customer (name, email, password) values ('Carol', 'cbroggio4@skyrock.com', 'UpL4WssvxA');
insert into customer (name, email, password) values ('Michel', 'mcarverhill5@businessinsider.com', 'b2lXj7vU9');
insert into customer (name, email, password) values ('Lionel', 'lmccaffrey6@opera.com', 'fEJuyzHn11');
insert into customer (name, email, password) values ('Adara', 'agetsham7@php.net', 'kvyU9virRO');
insert into customer (name, email, password) values ('Roseanna', 'rvermer8@dagondesign.com', 'flsq0MUn');
insert into customer (name, email, password) values ('Jennica', 'jlinebarger9@godaddy.com', 'Al4f4cbw5D');
insert into customer (name, email, password) values ('Tirrell', 'trosenstocka@google.ru', 'IDYZtEkHKav');
insert into customer (name, email, password) values ('Erskine', 'ecanbyb@princeton.edu', 'QsBEC3tIq74');
insert into customer (name, email, password) values ('Della', 'djanuszkiewiczc@instagram.com', 'ko8GEugegtXB');
insert into customer (name, email, password) values ('Jessamine', 'jborthramd@goo.gl', 'tPLEKzwtRs');
insert into customer (name, email, password) values ('Tonie', 'tbarcae@instagram.com', 'ttl50j');
insert into customer (name, email, password) values ('Fanchon', 'fyaldenf@chicagotribune.com', 'WYDTHQwu');
insert into customer (name, email, password) values ('Carree', 'cstickfordg@1688.com', 'tTYFkuduATad');
insert into customer (name, email, password) values ('Jess', 'jbraunterh@cbslocal.com', 'UAWL8AsGV');
insert into customer (name, email, password) values ('Tomkin', 'tgoldneyi@miibeian.gov.cn', 'sSl1l0P');
insert into customer (name, email, password) values ('Kristal', 'kdidelloj@themeforest.net', 'THl07kRo1K');
insert into customer (name, email, password) values ('Tiebout', 'tlesurfk@cnn.com', 'FMA7Ida');
insert into customer (name, email, password) values ('Moe', 'mclaeskensl@shop-pro.jp', 'pPZBMQ');
insert into customer (name, email, password) values ('Tiphani', 'tgirkinm@hugedomains.com', 'aZVylEb5qdA');
insert into customer (name, email, password) values ('Wileen', 'weamn@alibaba.com', 'ethtiBPMJ');
insert into customer (name, email, password) values ('Reinwald', 'rtooko@imdb.com', 'CPhCnMaLD');
insert into customer (name, email, password) values ('Avram', 'apemberyp@soup.io', 'PVp0b8oOcN5');
insert into customer (name, email, password) values ('Roger', 'roffieldq@live.com', 'UMwTsLxIuD');
insert into customer (name, email, password) values ('Baird', 'bmiddletonr@taobao.com', 'YMAbjTw1');
insert into customer (name, email, password) values ('Vivyan', 'vjubbs@europa.eu', 'qHLs3tBJ');
insert into customer (name, email, password) values ('Isidor', 'irodgersont@ucla.edu', 'BqZYYu1d1');
insert into customer (name, email, password) values ('Harrietta', 'hgrinovu@skype.com', 'tdEbOF4ELxAF');
insert into customer (name, email, password) values ('Irma', 'inassiv@thetimes.co.uk', 'Tz9t9oKtr2se');
insert into customer (name, email, password) values ('Caprice', 'crumblew@usa.gov', 'Tjcc2IwK1Rxm');
insert into customer (name, email, password) values ('Aldridge', 'abooix@liveinternet.ru', 'x79JbE');
insert into customer (name, email, password) values ('Augusto', 'akesony@sciencedaily.com', 'l2i1aiBmo4');
insert into customer (name, email, password) values ('Larisa', 'ledinboroughz@timesonline.co.uk', 'HAaPs7NsN');
insert into customer (name, email, password) values ('Kelly', 'ktapner10@facebook.com', 'cZd1vm2i0O2');
insert into customer (name, email, password) values ('Brit', 'bthowes11@usda.gov', 'gdjLdwKFUlZ');
insert into customer (name, email, password) values ('Elsa', 'eyankishin12@google.ru', 'XpfgZa');
insert into customer (name, email, password) values ('Say', 'sjanssens13@patch.com', 'WuTvp3oCNJ');
insert into customer (name, email, password) values ('Trace', 'thattoe14@latimes.com', 'lAqskC');
insert into customer (name, email, password) values ('Shannon', 'stattersfield15@arstechnica.com', 'RNmWzXKN5u7r');
insert into customer (name, email, password) values ('Delly', 'dfellman16@elegantthemes.com', 'ePJgJcn38');
insert into customer (name, email, password) values ('Sollie', 'sleat17@4shared.com', 'cGBhvKS1a5');
insert into customer (name, email, password) values ('Cathi', 'cdubery18@pagesperso-orange.fr', 'g0oDUOS7');
insert into customer (name, email, password) values ('Dominga', 'diacobucci19@unicef.org', 'b8YuSIC');
insert into customer (name, email, password) values ('Owen', 'ocastilljo1a@kickstarter.com', 'C4Ic7oYB0q6L');

# customer address

insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (1, '20', 'Bartillon', 'Serra de Santa Marinha', '3542');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (2, '0', 'Elmside', 'Estoril', '8743');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (3, '8', 'Park Meadow', 'Sanok', '56207');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (4, '91', 'Forest Run', 'Pandan Niog', '40');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (5, '03', 'Bluestem', 'Krajan', '7');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (6, '0463', 'Reinke', 'Austin', '6662');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (7, '84', 'Kensington', 'Altıağac', '5');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (8, '340', 'Garrison', 'Jiangya', '5');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (9, '7806', 'Johnson', 'Yafan', '6');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (10, '8', 'Dapin', 'Pisões', '3932');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (11, '34783', 'Sundown', 'New York City', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (12, '8770', 'Mesta', 'Maloarkhangel’sk', '80');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (13, '4', 'Longview', 'Rambatan', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (14, '347', 'Schlimgen', 'Vitoria-Gasteiz', '76168');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (15, '7554', 'Johnson', 'Арачиново', '9189');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (16, '542', 'Continental', 'Vigo', '96');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (17, '42622', 'Sunnyside', 'Kesamben', '3');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (18, '31', 'Nevada', 'Geghanist', '85088');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (19, '5928', 'Grasskamp', 'Koímisi', '33');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (20, '201', 'Dakota', 'Marseille', '85449');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (21, '08798', 'Packers', 'Lushnjë', '18');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (22, '99', 'Fisk', 'Serrana', '17');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (23, '74', 'New Castle', 'Jiangdulu', '01720');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (24, '87', 'Caliangt', 'T’et’ri Tsqaro', '35');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (25, '401', 'Shasta', 'Caper', '816');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (26, '6', 'Mallard', 'Campinas', '73288');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (27, '38774', 'Iowa', 'Manzanares', '74');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (28, '4407', 'Mayer', 'Ipoh', '864');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (29, '11', 'Annamark', 'El Tejocote', '3803');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (30, '03', 'Anniversary', 'Zhouhu', '70287');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (31, '051', 'Paget', 'Union', '63');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (32, '3', 'Dwight', 'General Vedia', '1895');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (33, '56', 'Karstens', 'Dongle', '8784');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (34, '035', 'Ridgeway', 'Ihosy', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (35, '0616', 'Butterfield', 'Xuhui', '7');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (36, '19', 'Oak', 'Mueang Phuket', '3');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (37, '49654', 'Ronald Regan', 'Kardítsa', '90924');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (38, '0687', 'Cody', 'Kolpashevo', '019');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (39, '46', 'Forest Dale', 'Yichun', '2630');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (40, '8224', 'Waxwing', 'Fushan', '53433');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (41, '16', 'Cody', 'Dazhipo', '9245');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (42, '355', 'Everett', 'Heishui', '9');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (43, '5834', 'Bluestem', 'Rikitea', '0556');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (44, '393', 'Sullivan', 'Yaodu', '20096');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (45, '88', 'Coolidge', 'Liutangting', '15924');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (46, '2820', 'High Crossing', 'Sūq al Khamīs', '7320');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (47, '78', 'Packers', 'Abdurahmoni Jomí', '781');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (48, '522', 'Butterfield', 'Shufeng', '67');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (49, '7', 'Veith', 'San Antonio', '19549');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (50, '2498', 'Orin', 'Tinabogan', '154');

# customer mobile

insert into customer_mobile (customer_id, mobile) values (1, '0771121415');
insert into customer_mobile (customer_id, mobile) values (2, '0741151312');
insert into customer_mobile (customer_id, mobile) values (3, '0771121415');
insert into customer_mobile (customer_id, mobile) values (4, '0771121415');
insert into customer_mobile (customer_id, mobile) values (5, '0741151312');
insert into customer_mobile (customer_id, mobile) values (6, '0741151312');
insert into customer_mobile (customer_id, mobile) values (7, '0741151312');
insert into customer_mobile (customer_id, mobile) values (8, '0771121415');
insert into customer_mobile (customer_id, mobile) values (9, '0717112145');
insert into customer_mobile (customer_id, mobile) values (10, '0717112145');
insert into customer_mobile (customer_id, mobile) values (11, '0771121415');
insert into customer_mobile (customer_id, mobile) values (12, '0717112145');
insert into customer_mobile (customer_id, mobile) values (13, '0741151312');
insert into customer_mobile (customer_id, mobile) values (14, '0787849898');
insert into customer_mobile (customer_id, mobile) values (15, '0787849898');
insert into customer_mobile (customer_id, mobile) values (16, '0771121415');
insert into customer_mobile (customer_id, mobile) values (17, '0787849898');
insert into customer_mobile (customer_id, mobile) values (18, '0741151312');
insert into customer_mobile (customer_id, mobile) values (19, '0717112145');
insert into customer_mobile (customer_id, mobile) values (20, '0787849898');
insert into customer_mobile (customer_id, mobile) values (21, '0771121415');
insert into customer_mobile (customer_id, mobile) values (22, '0771121415');
insert into customer_mobile (customer_id, mobile) values (23, '0741151312');
insert into customer_mobile (customer_id, mobile) values (24, '0717112145');
insert into customer_mobile (customer_id, mobile) values (25, '0787849898');
insert into customer_mobile (customer_id, mobile) values (26, '0717112145');
insert into customer_mobile (customer_id, mobile) values (27, '0787849898');
insert into customer_mobile (customer_id, mobile) values (28, '0717112145');
insert into customer_mobile (customer_id, mobile) values (29, '0717112145');
insert into customer_mobile (customer_id, mobile) values (30, '0787849898');
insert into customer_mobile (customer_id, mobile) values (31, '0741151312');
insert into customer_mobile (customer_id, mobile) values (32, '0771121415');
insert into customer_mobile (customer_id, mobile) values (33, '0741151312');
insert into customer_mobile (customer_id, mobile) values (34, '0717112145');
insert into customer_mobile (customer_id, mobile) values (35, '0717112145');
insert into customer_mobile (customer_id, mobile) values (36, '0717112145');
insert into customer_mobile (customer_id, mobile) values (37, '0741151312');
insert into customer_mobile (customer_id, mobile) values (38, '0787849898');
insert into customer_mobile (customer_id, mobile) values (39, '0717112145');
insert into customer_mobile (customer_id, mobile) values (40, '0771121415');
insert into customer_mobile (customer_id, mobile) values (41, '0741151312');
insert into customer_mobile (customer_id, mobile) values (42, '0787849898');
insert into customer_mobile (customer_id, mobile) values (43, '0771121415');
insert into customer_mobile (customer_id, mobile) values (44, '0771121415');
insert into customer_mobile (customer_id, mobile) values (45, '0717112145');
insert into customer_mobile (customer_id, mobile) values (46, '0717112145');
insert into customer_mobile (customer_id, mobile) values (47, '0717112145');
insert into customer_mobile (customer_id, mobile) values (48, '0741151312');
insert into customer_mobile (customer_id, mobile) values (49, '0771121415');
insert into customer_mobile (customer_id, mobile) values (50, '0717112145');
