use texas_e_store;

# customer

insert into customer (email, password, first_name, last_name) values ('hiruni@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Hiruni', 'Silva');
insert into customer (email, password, first_name, last_name) values ('ablain0@cmu.edu', 'ozO9iE0D', 'Annalise', 'Blain');
insert into customer (email, password, first_name, last_name) values ('cbraun1@wsj.com', 'hyIn0uN69jm', 'Cobb', 'Braun');
insert into customer (email, password, first_name, last_name) values ('fshopcott2@opensource.org', 'HYSKLcZ4', 'Felisha', 'Shopcott');
insert into customer (email, password, first_name, last_name) values ('oenrietto3@gnu.org', 'cTt2Vf3PZMIR', 'Orion', 'Enrietto');
insert into customer (email, password, first_name, last_name) values ('maspinall4@wordpress.com', 'QFqAxLGDjTr7', 'Marnia', 'Aspinall');
insert into customer (email, password, first_name, last_name) values ('hohaire5@unblog.fr', 'G8wGZBsMcBZ', 'Hattie', 'O''Haire');
insert into customer (email, password, first_name, last_name) values ('nburnes6@google.com.br', 'jgpDvEBYvd', 'Norton', 'Burnes');
insert into customer (email, password, first_name, last_name) values ('gweddeburnscrimgeour7@posterous.com', '5J5wfoQZXBkq', 'Gennie', 'Weddeburn - Scrimgeour');
insert into customer (email, password, first_name, last_name) values ('gscrimshaw8@google.co.jp', 'E55fZ92bH', 'Geordie', 'Scrimshaw');
insert into customer (email, password, first_name, last_name) values ('bstowgill9@amazonaws.com', 'j0DXzsTVAF4', 'Booth', 'Stowgill');
insert into customer (email, password, first_name, last_name) values ('dprobyna@smh.com.au', 'tmpbSuO', 'Denny', 'Probyn');
insert into customer (email, password, first_name, last_name) values ('scullinaneb@elegantthemes.com', 'kmC5Dj1h', 'Sammy', 'Cullinane');
insert into customer (email, password, first_name, last_name) values ('gbrisardc@tripod.com', 'X4ANy0rvgSn', 'Gunar', 'Brisard');
insert into customer (email, password, first_name, last_name) values ('bashbrookd@barnesandnoble.com', 'XlnAIv', 'Billie', 'Ashbrook');
insert into customer (email, password, first_name, last_name) values ('dkille@comcast.net', '3zmOqFnEm', 'Dina', 'Kill');
insert into customer (email, password, first_name, last_name) values ('vboyntonf@merriam-webster.com', 'SWOx2mCI', 'Valenka', 'Boynton');
insert into customer (email, password, first_name, last_name) values ('trennoldsg@paginegialle.it', 'w62otAITec5i', 'Terrell', 'Rennolds');
insert into customer (email, password, first_name, last_name) values ('cbattlesonh@reddit.com', 'mAsgjGo4Gz', 'Cordey', 'Battleson');
insert into customer (email, password, first_name, last_name) values ('rchevini@soup.io', 'lr24BrdcBbVC', 'Raffarty', 'Chevin');
insert into customer (email, password, first_name, last_name) values ('vmillichipj@themeforest.net', 'LJtDtiI2C', 'Vaclav', 'Millichip');
insert into customer (email, password, first_name, last_name) values ('trobertetk@angelfire.com', 'l698UQWRmLe9', 'Templeton', 'Robertet');
insert into customer (email, password, first_name, last_name) values ('jiacavonel@wix.com', 'R1utar', 'Jaine', 'Iacavone');
insert into customer (email, password, first_name, last_name) values ('ezylberdikm@edublogs.org', 'esTJxyw2OhFm', 'Edgar', 'Zylberdik');
insert into customer (email, password, first_name, last_name) values ('vspieghtn@ustream.tv', 'reW8tpT7sdUl', 'Virginia', 'Spieght');
insert into customer (email, password, first_name, last_name) values ('sbrushneeno@ning.com', 'DVT5oxH4zh', 'Sawyere', 'Brushneen');
insert into customer (email, password, first_name, last_name) values ('fbircherp@opensource.org', '3SUN8bOe4OVp', 'Fae', 'Bircher');
insert into customer (email, password, first_name, last_name) values ('ugrishakovq@businessweek.com', 'xH1EwDZGuFQ', 'Ursa', 'Grishakov');
insert into customer (email, password, first_name, last_name) values ('cbreder@ca.gov', 'UtjTWz1E', 'Corrianne', 'Brede');
insert into customer (email, password, first_name, last_name) values ('mmcnirlins@woothemes.com', 'St3uJ53MdJKP', 'Marcellus', 'McNirlin');
insert into customer (email, password, first_name, last_name) values ('zbumbyt@about.com', 'doPlKTkTtdWN', 'Zarla', 'Bumby');
insert into customer (email, password, first_name, last_name) values ('vhartrightu@patch.com', '6yf5N4oSdFN', 'Vinni', 'Hartright');
insert into customer (email, password, first_name, last_name) values ('sdonalsonv@ft.com', 'GxEMBHvP', 'Stearn', 'Donalson');
insert into customer (email, password, first_name, last_name) values ('rtudhopew@auda.org.au', 'GZyNzdz', 'Rosanne', 'Tudhope');
insert into customer (email, password, first_name, last_name) values ('mhueyx@bluehost.com', '10xR4K4', 'Mabelle', 'Huey');
insert into customer (email, password, first_name, last_name) values ('cpetrasy@webmd.com', 'Ae4vAD3ZFk', 'Corrianne', 'Petras');
insert into customer (email, password, first_name, last_name) values ('lpagelz@g.co', 'GLRuV6aFgRL', 'Lotte', 'Pagel');
insert into customer (email, password, first_name, last_name) values ('livantyev10@example.com', 'csswOA', 'Lexie', 'Ivantyev');
insert into customer (email, password, first_name, last_name) values ('ttuttiett11@vinaora.com', 'dA2kYIFjTLiB', 'Tad', 'Tuttiett');
insert into customer (email, password, first_name, last_name) values ('kblundin12@fastcompany.com', 'srhLCHECT', 'Katerina', 'Blundin');
insert into customer (email, password, first_name, last_name) values ('mgillitt13@goodreads.com', 'up9N7V5', 'Matthiew', 'Gillitt');
insert into customer (email, password, first_name, last_name) values ('hjencken14@surveymonkey.com', 'oSr7o8sXf7', 'Harland', 'Jencken');
insert into customer (email, password, first_name, last_name) values ('dhue15@jalbum.net', 'PVcfUp', 'Dorie', 'Hue');
insert into customer (email, password, first_name, last_name) values ('gdollimore16@oaic.gov.au', 'VVcD3m', 'Guinevere', 'Dollimore');
insert into customer (email, password, first_name, last_name) values ('blouthe17@eventbrite.com', 'mapQhsKF', 'Berne', 'Louthe');
insert into customer (email, password, first_name, last_name) values ('wkibel18@mlb.com', 'qCqswbTd', 'Wittie', 'Kibel');
insert into customer (email, password, first_name, last_name) values ('opexton19@state.gov', 'S9bvOQaw6VKY', 'Olive', 'Pexton');
insert into customer (email, password, first_name, last_name) values ('csemken1a@utexas.edu', 'AJsvnrloot', 'Colby', 'Semken');
insert into customer (email, password, first_name, last_name) values ('ecottrill1b@merriam-webster.com', 'gEMGDJrMw', 'Emmi', 'Cottrill');
insert into customer (email, password, first_name, last_name) values ('adeeley1c@vkontakte.ru', 'HLUA5p', 'Arda', 'Deeley');
insert into customer (email, password, first_name, last_name) values ('cpoore1d@ow.ly', 'UbpSC97ev', 'Claudius', 'Poore');

# customer address

insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (1, '20', 'Bartillon', 'Serra de Santa Marinha', '3542');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (2, '0', 'Elmside', 'Estoril', '8743');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (3, '8', 'Park Meadow', 'Sanok', '56207');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (4, '91', 'Forest Run', 'Pandan Niog', '40');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (5, '03', 'Bluestem', 'Krajan', '7');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (6, '0463', 'Reinke', 'Austin', '6662');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (7, '84', 'Kensington', 'Altıağac', '5');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (8, '340', 'Garrison', 'Jiangya', '5');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (9, '7806', 'Johnson', 'Yafan', '6');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (10, '8', 'Dapin', 'Pisões', '3932');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (11, '34783', 'Sundown', 'New York City', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (12, '8770', 'Mesta', 'Maloarkhangel’sk', '80');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (13, '4', 'Longview', 'Rambatan', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (14, '347', 'Schlimgen', 'Vitoria-Gasteiz', '76168');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (15, '7554', 'Johnson', 'Арачиново', '9189');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (16, '542', 'Continental', 'Vigo', '96');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (17, '42622', 'Sunnyside', 'Kesamben', '3');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (18, '31', 'Nevada', 'Geghanist', '85088');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (19, '5928', 'Grasskamp', 'Koímisi', '33');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (20, '201', 'Dakota', 'Marseille', '85449');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (21, '08798', 'Packers', 'Lushnjë', '18');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (22, '99', 'Fisk', 'Serrana', '17');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (23, '74', 'New Castle', 'Jiangdulu', '01720');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (24, '87', 'Caliangt', 'T’et’ri Tsqaro', '35');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (25, '401', 'Shasta', 'Caper', '816');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (26, '6', 'Mallard', 'Campinas', '73288');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (27, '38774', 'Iowa', 'Manzanares', '74');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (28, '4407', 'Mayer', 'Ipoh', '864');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (29, '11', 'Annamark', 'El Tejocote', '3803');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (30, '03', 'Anniversary', 'Zhouhu', '70287');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (31, '051', 'Paget', 'Union', '63');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (32, '3', 'Dwight', 'General Vedia', '1895');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (33, '56', 'Karstens', 'Dongle', '8784');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (34, '035', 'Ridgeway', 'Ihosy', '0');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (35, '0616', 'Butterfield', 'Xuhui', '7');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (36, '19', 'Oak', 'Mueang Phuket', '3');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (37, '49654', 'Ronald Regan', 'Kardítsa', '90924');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (38, '0687', 'Cody', 'Kolpashevo', '019');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (39, '46', 'Forest Dale', 'Yichun', '2630');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (40, '8224', 'Waxwing', 'Fushan', '53433');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (41, '16', 'Cody', 'Dazhipo', '9245');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (42, '355', 'Everett', 'Heishui', '9');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (43, '5834', 'Bluestem', 'Rikitea', '0556');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (44, '393', 'Sullivan', 'Yaodu', '20096');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (45, '88', 'Coolidge', 'Liutangting', '15924');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (46, '2820', 'High Crossing', 'Sūq al Khamīs', '7320');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (47, '78', 'Packers', 'Abdurahmoni Jomí', '781');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (48, '522', 'Butterfield', 'Shufeng', '67');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (49, '7', 'Veith', 'San Antonio', '19549');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (50, '2498', 'Orin', 'Tinabogan', '154');

# customer mobile

insert into customer_mobile (customer_id, mobile) values (1, '0771121415');
insert into customer_mobile (customer_id, mobile) values (2, '0741151312');
insert into customer_mobile (customer_id, mobile) values (3, '0771121415');
insert into customer_mobile (customer_id, mobile) values (4, '0771121415');
insert into customer_mobile (customer_id, mobile) values (5, '0741151312');
insert into customer_mobile (customer_id, mobile) values (6, '0741151312');
insert into customer_mobile (customer_id, mobile) values (7, '0741151312');
insert into customer_mobile (customer_id, mobile) values (8, '0771121415');
insert into customer_mobile (customer_id, mobile) values (9, '0717112145');
insert into customer_mobile (customer_id, mobile) values (10, '0717112145');
insert into customer_mobile (customer_id, mobile) values (11, '0771121415');
insert into customer_mobile (customer_id, mobile) values (12, '0717112145');
insert into customer_mobile (customer_id, mobile) values (13, '0741151312');
insert into customer_mobile (customer_id, mobile) values (14, '0787849898');
insert into customer_mobile (customer_id, mobile) values (15, '0787849898');
insert into customer_mobile (customer_id, mobile) values (16, '0771121415');
insert into customer_mobile (customer_id, mobile) values (17, '0787849898');
insert into customer_mobile (customer_id, mobile) values (18, '0741151312');
insert into customer_mobile (customer_id, mobile) values (19, '0717112145');
insert into customer_mobile (customer_id, mobile) values (20, '0787849898');
insert into customer_mobile (customer_id, mobile) values (21, '0771121415');
insert into customer_mobile (customer_id, mobile) values (22, '0771121415');
insert into customer_mobile (customer_id, mobile) values (23, '0741151312');
insert into customer_mobile (customer_id, mobile) values (24, '0717112145');
insert into customer_mobile (customer_id, mobile) values (25, '0787849898');
insert into customer_mobile (customer_id, mobile) values (26, '0717112145');
insert into customer_mobile (customer_id, mobile) values (27, '0787849898');
insert into customer_mobile (customer_id, mobile) values (28, '0717112145');
insert into customer_mobile (customer_id, mobile) values (29, '0717112145');
insert into customer_mobile (customer_id, mobile) values (30, '0787849898');
insert into customer_mobile (customer_id, mobile) values (31, '0741151312');
insert into customer_mobile (customer_id, mobile) values (32, '0771121415');
insert into customer_mobile (customer_id, mobile) values (33, '0741151312');
insert into customer_mobile (customer_id, mobile) values (34, '0717112145');
insert into customer_mobile (customer_id, mobile) values (35, '0717112145');
insert into customer_mobile (customer_id, mobile) values (36, '0717112145');
insert into customer_mobile (customer_id, mobile) values (37, '0741151312');
insert into customer_mobile (customer_id, mobile) values (38, '0787849898');
insert into customer_mobile (customer_id, mobile) values (39, '0717112145');
insert into customer_mobile (customer_id, mobile) values (40, '0771121415');
insert into customer_mobile (customer_id, mobile) values (41, '0741151312');
insert into customer_mobile (customer_id, mobile) values (42, '0787849898');
insert into customer_mobile (customer_id, mobile) values (43, '0771121415');
insert into customer_mobile (customer_id, mobile) values (44, '0771121415');
insert into customer_mobile (customer_id, mobile) values (45, '0717112145');
insert into customer_mobile (customer_id, mobile) values (46, '0717112145');
insert into customer_mobile (customer_id, mobile) values (47, '0717112145');
insert into customer_mobile (customer_id, mobile) values (48, '0741151312');
insert into customer_mobile (customer_id, mobile) values (49, '0771121415');
insert into customer_mobile (customer_id, mobile) values (50, '0717112145');
