use texas_e_store;

# admin

insert into admin (name, email, password) values  ('Achira', 'achira@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka');
insert into admin (name, email, password) values ('Chaturanga', 'chathuranga@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka');
insert into admin (name, email, password) values ('Sasitha', 'sasitha@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka');
insert into admin (name, email, password) values ('Thamindu', 'thamindu@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka');
insert into admin (name, email, password) values ('Shilpa', 'shilpa@gmail.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka');

#categories

insert into category(category_name) values ('Mobiles');
insert into category(category_name) values ('Tablets');
insert into category(category_name) values ('Laptops');
insert into category(category_name) values ('Cameras');
insert into category(category_name) values ('Monitors');
insert into category(category_name) values ('Smart Watches');
insert into category(category_name) values ('External Storages');
insert into category(category_name) values ('Desktops');
insert into category(category_name) values ('Smart TVs');
insert into category(category_name) values ('Routers');
insert into category(category_name) values ('Power Banks');
insert into category(category_name) values ('Keyboards');
insert into category(category_name) values ('Memory Cards');
insert into category(category_name) values ('Mice');
insert into category(category_name) values ('Printers');

insert into sub_category (sub_category_name) values ('Apple');
insert into sub_category (sub_category_name) values ('Nikon');
insert into sub_category (sub_category_name) values ('SanDisk');
insert into sub_category (sub_category_name) values ('Transcend');
insert into sub_category (sub_category_name) values ('Samsung');
insert into sub_category (sub_category_name) values ('Nokia');
insert into sub_category (sub_category_name) values ('Hp');
insert into sub_category (sub_category_name) values ('Asus');
insert into sub_category (sub_category_name) values ('Acer');
insert into sub_category (sub_category_name) values ('Huawei');
insert into sub_category (sub_category_name) values ('ZTE');
insert into sub_category (sub_category_name) values ('PROLiNK');
insert into sub_category (sub_category_name) values ('Wireless');
insert into sub_category (sub_category_name) values ('4 G');
insert into sub_category (sub_category_name) values ('ADSL');
insert into sub_category (sub_category_name) values ('Gaming');
insert into sub_category (sub_category_id, sub_category_name) values (17, 'Dell');
insert into sub_category (sub_category_id, sub_category_name) values (19, 'Logitech');
insert into sub_category (sub_category_id, sub_category_name) values (20, 'Corsair');
INSERT INTO sub_category (sub_category_id, sub_category_name) VALUES (21,'Canon');
INSERT INTO sub_category (sub_category_id, sub_category_name) VALUES (22,'MSI');

INSERT INTO category_link (category_id, sub_category_id) VALUES (1,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (2,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (3,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (6,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (9,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (12,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,1);
INSERT INTO category_link (category_id, sub_category_id) VALUES (4,2);
INSERT INTO category_link (category_id, sub_category_id) VALUES (7,3);
INSERT INTO category_link (category_id, sub_category_id) VALUES (13,3);
INSERT INTO category_link (category_id, sub_category_id) VALUES (7,4);
INSERT INTO category_link (category_id, sub_category_id) VALUES (13,4);
INSERT INTO category_link (category_id, sub_category_id) VALUES (1,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (2,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (6,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (7,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (9,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,5);
INSERT INTO category_link (category_id, sub_category_id) VALUES (1,6);
INSERT INTO category_link (category_id, sub_category_id) VALUES (9,6);
INSERT INTO category_link (category_id, sub_category_id) VALUES (3,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (12,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (15,7);
INSERT INTO category_link (category_id, sub_category_id) VALUES (3,8);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,8);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,8);
INSERT INTO category_link (category_id, sub_category_id) VALUES (12,8);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,8);
INSERT INTO category_link (category_id, sub_category_id) VALUES (3,9);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,9);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,9);
INSERT INTO category_link (category_id, sub_category_id) VALUES (12,9);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,9);
INSERT INTO category_link (category_id, sub_category_id) VALUES (1,10);
INSERT INTO category_link (category_id, sub_category_id) VALUES (2,10);
INSERT INTO category_link (category_id, sub_category_id) VALUES (10,11);
INSERT INTO category_link (category_id, sub_category_id) VALUES (10,12);
INSERT INTO category_link (category_id, sub_category_id) VALUES (10,13);
INSERT INTO category_link (category_id, sub_category_id) VALUES (10,14);
INSERT INTO category_link (category_id, sub_category_id) VALUES (10,15);
INSERT INTO category_link (category_id, sub_category_id) VALUES (8,16);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,16);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,17);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,17);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,19);
INSERT INTO category_link (category_id, sub_category_id) VALUES (12,20);
INSERT INTO category_link (category_id, sub_category_id) VALUES (14,20);
INSERT INTO category_link (category_id, sub_category_id) VALUES (4,21);
INSERT INTO category_link (category_id, sub_category_id) VALUES (5,23);
