insert into customer (email, password, first_name, last_name) values ('hiruni@email.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Hiruni', 'Silva');
insert into customer (email, password, first_name, last_name) values ('paughton0@google.fr', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Patrice', 'Aughton');
insert into customer (email, password, first_name, last_name) values ('pbartozzi1@exblog.jp', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Pat', 'Bartozzi');
insert into customer (email, password, first_name, last_name) values ('scockayme2@squarespace.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Shandie', 'Cockayme');
insert into customer (email, password, first_name, last_name) values ('trosenfield3@miitbeian.gov.cn', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Thornie', 'Rosenfield');
insert into customer (email, password, first_name, last_name) values ('asulter4@fc2.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Adrian', 'Sulter');
insert into customer (email, password, first_name, last_name) values ('koliver5@tinypic.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Kristyn', 'Oliver');
insert into customer (email, password, first_name, last_name) values ('cdugald6@deliciousdays.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Cecil', 'Dugald');
insert into customer (email, password, first_name, last_name) values ('ekerin7@is.gd', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Elana', 'Kerin');
insert into customer (email, password, first_name, last_name) values ('wduplantier8@cnet.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Ware', 'Du Plantier');
insert into customer (email, password, first_name, last_name) values ('ddeeble9@twitpic.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Dionis', 'Deeble');
insert into customer (email, password, first_name, last_name) values ('afearsa@yellowbook.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Allistir', 'Fears');
insert into customer (email, password, first_name, last_name) values ('callumb@alexa.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Channa', 'Allum');
insert into customer (email, password, first_name, last_name) values ('stregonnac@slideshare.net', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Sherrie', 'Tregonna');
insert into customer (email, password, first_name, last_name) values ('hdabsd@squarespace.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Humbert', 'Dabs');
insert into customer (email, password, first_name, last_name) values ('sghelerdinie@cdc.gov', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Sarge', 'Ghelerdini');
insert into customer (email, password, first_name, last_name) values ('bmckirtonf@nydailynews.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Billie', 'McKirton');
insert into customer (email, password, first_name, last_name) values ('llippittg@weather.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Leda', 'Lippitt');
insert into customer (email, password, first_name, last_name) values ('wbasanth@a8.net', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Wayland', 'Basant');
insert into customer (email, password, first_name, last_name) values ('fleybornei@naver.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Fancy', 'Leyborne');
insert into customer (email, password, first_name, last_name) values ('kwelchmanj@businesswire.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Kacy', 'Welchman');
insert into customer (email, password, first_name, last_name) values ('fhullyk@yellowbook.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Florry', 'Hully');
insert into customer (email, password, first_name, last_name) values ('bclinchl@com.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Bobine', 'Clinch');
insert into customer (email, password, first_name, last_name) values ('rbeadonm@blogs.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Richy', 'Beadon');
insert into customer (email, password, first_name, last_name) values ('ddietzlern@usa.gov', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Dar', 'Dietzler');
insert into customer (email, password, first_name, last_name) values ('mfennello@w3.org', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Maddie', 'Fennell');
insert into customer (email, password, first_name, last_name) values ('lvasichevp@mayoclinic.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Laney', 'Vasichev');
insert into customer (email, password, first_name, last_name) values ('abeangeq@sina.com.cn', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Alicia', 'Beange');
insert into customer (email, password, first_name, last_name) values ('gpoler@chron.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Geoffry', 'Pole');
insert into customer (email, password, first_name, last_name) values ('hedgins@apache.org', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Hamish', 'Edgin');
insert into customer (email, password, first_name, last_name) values ('kmillst@answers.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Karlens', 'Mills');
insert into customer (email, password, first_name, last_name) values ('falmacku@google.ca', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Francis', 'Almack');
insert into customer (email, password, first_name, last_name) values ('jprovestv@wiley.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Jacquenetta', 'Provest');
insert into customer (email, password, first_name, last_name) values ('dsaladinew@photobucket.com', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Dayna', 'Saladine');
insert into customer (email, password, first_name, last_name) values ('cmierex@cbc.ca', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Cody', 'Miere');
insert into customer (email, password, first_name, last_name) values ('kcowperthwaitey@google.com.hk', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Klara', 'Cowperthwaite');
insert into customer (email, password, first_name, last_name) values ('achipperfieldz@google.com.hk', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Ari', 'Chipperfield');
insert into customer (email, password, first_name, last_name) values ('hchristoffels10@archive.org', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Helsa', 'Christoffels');
insert into customer (email, password, first_name, last_name) values ('mbosward11@i2i.jp', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Mortimer', 'Bosward');
insert into customer (email, password, first_name, last_name) values ('kcockran12@irs.gov', '$2b$10$T98uZ8xm/c7GACggl/w5Re3KwBTwISbpBYYG1p9MyXi1A6njuc9ka', 'Keriann', 'Cockran');

# customer address

insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (1, '0451', 'Meadow Vale', 'New Cebu', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (2, '0140', 'John Wall', 'Ilagan', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (3, '0110', 'Meadow Vale', 'Acharnés', '00300');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (4, '0140', 'Coolidge', 'Sobral da Abelheira', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (5, '0451', 'Maple Wood', 'Vilares', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (6, '0451', 'Mayfield', 'Newmarket on Fergus', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (7, '0110', 'Hallows', 'Dourbali', '00300');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (8, '0124', 'Rutledge', 'Encañada', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (9, '0451', 'Dayton', 'Jobabo', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (10, '0451', 'Thackeray', 'Businga', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (11, '0451', 'Delaware', 'Shibīn al Kawm', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (12, '0140', 'Packers', 'Hewan', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (13, '0451', 'Duke', 'Höganäs', '00300');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (14, '0110', 'Hollow Ridge', 'Saharna', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (15, '0110', 'Express', 'Savigny-le-Temple', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (16, '0451', 'Doe Crossing', 'Nar''yan-Mar', '00400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (17, '0124', 'Anderson', 'Incheon', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (18, '0451', 'Mariners Cove', 'Rîbniţa', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (19, '0140', 'Cherokee', 'Shangju', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (20, '0124', 'School', 'Khanu Woralaksaburi', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (21, '0110', 'Mesta', 'Tampa', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (22, '0124', 'Texas', '‘Uqayribāt', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (23, '0110', 'Elmside', 'Arroyo Seco', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (24, '0110', 'Mariners Cove', 'Kermānshāh', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (25, '0110', 'Kinsman', 'Dongmazar', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (26, '0140', 'Porter', 'Huatajata', '00400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (27, '0140', 'Mitchell', 'Mishixiang', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (28, '0124', 'Longview', 'Vaiusu', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (29, '0451', 'Sutteridge', 'Ban Nahin', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (30, '0140', 'Riverside', '’Unābah', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (31, '0451', 'American Ash', 'Chybie', '00300');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (32, '0124', 'Heath', 'Tubualá', '00300');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (33, '0110', 'Mendota', 'Fushan', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (34, '0124', 'Eagle Crest', 'La Escondida', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (35, '0140', 'Dwight', 'Gonayiv', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (36, '0140', 'Rieder', 'Cabusao', '00400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (37, '0451', 'Hoffman', 'Jinquan', '12400');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (38, '0451', 'Maryland', 'Kolumbug', '00100');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (39, '0124', 'Summer Ridge', 'Shikou', '00200');
insert into customer_address (customer_id, po_box, street_name, city, postal_code) values (40, '0124', 'Summer Ridge', 'Shikou', '00200');


# customer mobile

insert into customer_mobile (customer_id, mobile) values (1, '0771121415');
insert into customer_mobile (customer_id, mobile) values (2, '0741151312');
insert into customer_mobile (customer_id, mobile) values (3, '0771121415');
insert into customer_mobile (customer_id, mobile) values (4, '0771121415');
insert into customer_mobile (customer_id, mobile) values (5, '0741151312');
insert into customer_mobile (customer_id, mobile) values (6, '0741151312');
insert into customer_mobile (customer_id, mobile) values (7, '0741151312');
insert into customer_mobile (customer_id, mobile) values (8, '0771121415');
insert into customer_mobile (customer_id, mobile) values (9, '0717112145');
insert into customer_mobile (customer_id, mobile) values (10, '0717112145');
insert into customer_mobile (customer_id, mobile) values (11, '0771121415');
insert into customer_mobile (customer_id, mobile) values (12, '0717112145');
insert into customer_mobile (customer_id, mobile) values (13, '0741151312');
insert into customer_mobile (customer_id, mobile) values (14, '0787849898');
insert into customer_mobile (customer_id, mobile) values (15, '0787849898');
insert into customer_mobile (customer_id, mobile) values (16, '0771121415');
insert into customer_mobile (customer_id, mobile) values (17, '0787849898');
insert into customer_mobile (customer_id, mobile) values (18, '0741151312');
insert into customer_mobile (customer_id, mobile) values (19, '0717112145');
insert into customer_mobile (customer_id, mobile) values (20, '0787849898');
insert into customer_mobile (customer_id, mobile) values (21, '0771121415');
insert into customer_mobile (customer_id, mobile) values (22, '0771121415');
insert into customer_mobile (customer_id, mobile) values (23, '0741151312');
insert into customer_mobile (customer_id, mobile) values (24, '0717112145');
insert into customer_mobile (customer_id, mobile) values (25, '0787849898');
insert into customer_mobile (customer_id, mobile) values (26, '0717112145');
insert into customer_mobile (customer_id, mobile) values (27, '0787849898');
insert into customer_mobile (customer_id, mobile) values (28, '0717112145');
insert into customer_mobile (customer_id, mobile) values (29, '0717112145');
insert into customer_mobile (customer_id, mobile) values (30, '0787849898');
insert into customer_mobile (customer_id, mobile) values (31, '0741151312');
insert into customer_mobile (customer_id, mobile) values (32, '0771121415');
insert into customer_mobile (customer_id, mobile) values (33, '0741151312');
insert into customer_mobile (customer_id, mobile) values (34, '0717112145');
insert into customer_mobile (customer_id, mobile) values (35, '0717112145');
insert into customer_mobile (customer_id, mobile) values (36, '0717112145');
insert into customer_mobile (customer_id, mobile) values (37, '0741151312');
insert into customer_mobile (customer_id, mobile) values (38, '0787849898');
insert into customer_mobile (customer_id, mobile) values (39, '0717112145');
insert into customer_mobile (customer_id, mobile) values (40, '0771121415');

